/**
 * ORGΛNON — THE HARDENING SPRINT (V45), Phase 3: THE SIDECAR FREEZE (S205, D95; P-14/DD-100).
 *
 * THE DIAGNOSIS (P-14, the research's V52 item — always a hardening item): the Python sidecar's reproducibility was ASSERTED
 * (requirements-studio.txt with unpinned numpy+scipy), never FROZEN — no lockfile, no exact-pin proof on a clean clone.
 *
 * THE FREEZE (DD-100): a committed uv.lock (src/backtest/py/uv.lock, generated by `uv lock` from pyproject.toml — the studio
 * verdict path's numpy+scipy). `uv sync --frozen` on a clone installs EXACTLY the locked wheels; then checkFrozenSet()
 * re-attests the frozen seven's byte-hashes. The wheels are the ENVIRONMENT; the seven .py/loop are the LAW — a wheel that
 * differs across platforms while the seven attest byte-identical is RECORDED (the environment moved, the law did not), never a
 * Halt. uv is the sidecar's INSTALLER, not a mass-path dependency (deps stay 2 — hono+zod).
 *
 * Pure: reads the committed uv.lock + pyproject + the frozen-set attestation. No network (the clone-sync proof is a separate
 * transcript, hardening-sidecar.json, produced by the sidecar-freeze script / the clean-machine test).
 */
import { readFileSync, existsSync } from "node:fs"
import { createHash } from "node:crypto"
import path from "node:path"
import { PKG_ROOT } from "./frozen"
import { checkFrozenSet } from "./frozen"

export namespace Sidecar {
  const sha256 = (b: string) => createHash("sha256").update(b).digest("hex")
  const LOCK = path.join(PKG_ROOT, "src", "backtest", "py", "uv.lock")
  const PYPROJECT = path.join(PKG_ROOT, "src", "backtest", "py", "pyproject.toml")

  export interface Frozen {
    ok: boolean
    lockCommitted: boolean
    lockSha: string | null
    pyprojectCommitted: boolean
    lockedPackages: string[]
    frozenSevenAttested: boolean
    frozenSevenCount: { ok: number; total: number }
    note: string
  }

  // the packages the lock pins (names, deduped) — the environment frozen for the clone.
  function lockedPackageNames(): string[] {
    if (!existsSync(LOCK)) return []
    const raw = readFileSync(LOCK, "utf8")
    const names = new Set<string>()
    for (const m of raw.matchAll(/^name = "([^"]+)"/gm)) names.add(m[1])
    names.delete("organon-sidecar") // the project itself, not a dependency
    return [...names].sort()
  }

  export function frozen(): Frozen {
    const lockCommitted = existsSync(LOCK)
    const pyprojectCommitted = existsSync(PYPROJECT)
    const lockSha = lockCommitted ? sha256(readFileSync(LOCK, "utf8")) : null
    const packages = lockedPackageNames()
    // the frozen seven: the 7 TRACKED frozen artifacts (6 .py + loop.ts). checkFrozenSet also lists gitignored/monorepo
    // artifacts as "absent" on a clone — those are the environment, not the law; the SEVEN are what must attest byte-identical.
    const fs = checkFrozenSet()
    const seven = fs.filter((c) => c.kind === "tracked-py" || c.id === "loop.ts")
    const sevenOk = seven.filter((c) => c.status === "ok").length
    const frozenSevenAttested = seven.length > 0 && sevenOk === seven.length
    const ok = lockCommitted && pyprojectCommitted && frozenSevenAttested && packages.length >= 2
    return {
      ok,
      lockCommitted,
      lockSha,
      pyprojectCommitted,
      lockedPackages: packages,
      frozenSevenAttested,
      frozenSevenCount: { ok: sevenOk, total: seven.length },
      note: ok
        ? `uv.lock committed (${lockSha!.slice(0, 12)}…, ${packages.length} packages: ${packages.join(", ")}); the frozen seven attest byte-identical (${sevenOk}/${seven.length}, 0 drift); uv sync --frozen reproduces the environment on a clone (S205/P-14). The wheels are the environment; the seven are the law.`
        : `sidecar freeze INCOMPLETE — lock:${lockCommitted} pyproject:${pyprojectCommitted} sevenAttested:${frozenSevenAttested} (${sevenOk}/${seven.length}) packages:${packages.length}`,
    }
  }

  // ── S205 — the Ship Gate verdict: the lock is committed + self-consistent + the frozen seven attest. ──
  export type Verdict = { ok: true; detail: string } | { ok: false; reason: string }
  export function verdict(): Verdict {
    const f = frozen()
    if (!f.lockCommitted) return { ok: false, reason: `src/backtest/py/uv.lock is NOT committed — the sidecar environment is asserted, not frozen (S205/P-14)` }
    if (!f.pyprojectCommitted) return { ok: false, reason: `src/backtest/py/pyproject.toml is NOT committed — uv sync --frozen has no manifest (S205)` }
    if (!f.frozenSevenAttested) return { ok: false, reason: `the frozen seven do NOT attest byte-identical (${f.frozenSevenCount.ok}/${f.frozenSevenCount.total}) — a frozen-core drift (S205)` }
    if (f.lockedPackages.length < 2) return { ok: false, reason: `the uv.lock pins fewer than 2 packages (${f.lockedPackages.length}) — the studio path needs numpy + scipy (S205)` }
    return { ok: true, detail: f.note }
  }
}
