#!/usr/bin/env bash
# ORGΛNON (standalone) — the studio trust battery: walls + the in-scope capability-floor tests.
set -euo pipefail
cd "$(dirname "$0")"
export NO_COLOR=1 XDG_DATA_HOME="$(mktemp -d)"
# DETERMINISTIC + OFFLINE (S20): force the Ask console into deterministic mode so the battery NEVER hits a live AI API,
# regardless of a developer's local .env (an empty shell var takes precedence over .env in Bun). The grounded-phrasing
# path is proven separately with injected mock providers/transports.
export GROQ_API_KEY= GOOGLE_AI_STUDIO_KEY= GEMINI_API_KEY= OPENAI_API_KEY= ANTHROPIC_API_KEY= OPENAI_COMPATIBLE_API_KEY= OPENAI_COMPATIBLE_BASE_URL=
bun test --timeout 30000 test/walls/ \
  test/organon/ledger.test.ts \
  test/organon/ledger_laundering.test.ts \
  test/organon/ledger_refragmentation.test.ts \
  test/organon/durable_ledger.test.ts \
  test/organon/studio_capture.test.ts \
  test/organon/studio_clocks.test.ts \
  test/organon/studio_agents.test.ts \
  test/organon/studio_enroll.test.ts \
  test/organon/studio_surfaces.test.ts \
  test/organon/studio_routes.test.ts \
  test/organon/studio_screens.test.ts \
  test/organon/studio_graph.test.ts \
  test/organon/scheduler_cadence.test.ts \
  test/organon/restore_drill.test.ts \
  test/organon/surface_fuzz.test.ts \
  test/organon/error_honesty.test.ts \
  test/organon/walk_fixes.test.ts \
  test/organon/walk_ledger.test.ts \
  test/organon/rejection_boundary.test.ts \
  test/organon/served_persistence.test.ts \
  test/organon/tense_scan.test.ts \
  test/organon/ledger_pollution.test.ts \
  test/organon/inventory_absences.test.ts \
  test/organon/repro_contracts.test.ts \
  test/organon/capability_matrix.test.ts \
  test/organon/dataplane_store.test.ts \
  test/organon/dataplane_differential.test.ts \
  test/organon/real_returns.test.ts \
  test/organon/transform_differential.test.ts \
  test/organon/funding_differential.test.ts \
  test/organon/goal_console.test.ts \
  test/organon/walk_v5.test.ts \
  test/organon/breadth_panel.test.ts \
  test/organon/cpcv_panel.test.ts \
  test/organon/voc_proposer.test.ts \
  test/organon/basis_domain.test.ts \
  test/organon/walk_v6.test.ts \
  test/organon/summary_differential.test.ts \
  test/organon/walls_deeper.test.ts \
  test/organon/experiments_answered.test.ts \
  test/organon/guided_builder.test.ts \
  test/organon/walk_v7.test.ts \
  test/organon/ensemble_law.test.ts \
  test/organon/ensemble_preconditions.test.ts \
  test/organon/ensemble_builder_whole.test.ts \
  test/organon/ensemble_pool.test.ts \
  test/organon/walk_v8.test.ts \
  test/organon/ensemble_verification.test.ts \
  test/organon/why_law.test.ts \
  test/organon/selection_door.test.ts \
  test/organon/parity_identity.test.ts \
  test/organon/why_panel.test.ts \
  test/organon/runner.test.ts \
  test/organon/walk_v9.test.ts \
  test/organon/why_verification.test.ts \
  test/organon/honesty_pins.test.ts \
  test/organon/honesty_record.test.ts \
  test/organon/honesty_data.test.ts \
  test/organon/honesty_scorecard.test.ts \
  test/organon/honesty_ui.test.ts \
  test/organon/honesty_funding.test.ts \
  test/organon/honesty_redteam.test.ts \
  test/organon/evidence_bundle.test.ts \
  test/organon/honesty_liquidity.test.ts \
  test/organon/honesty_unlock.test.ts \
  test/organon/honesty_counterparty.test.ts \
  test/organon/honesty_counterparty_contract.test.ts \
  test/organon/honesty_coverage.test.ts \
  test/organon/honesty_stamp.test.ts \
  test/organon/ask_router.test.ts \
  test/organon/ask_tools.test.ts \
  test/organon/ask_grounded.test.ts \
  test/organon/ask_ui.test.ts \
  test/organon/ask_interpret.test.ts \
  test/organon/ask_register.test.ts \
  test/organon/ask_truncation.test.ts \
  test/organon/ask_compare.test.ts \
  test/organon/crownjewel_redteam.test.ts \
  test/organon/findings_closed.test.ts \
  test/organon/findings_closed_p.test.ts \
  test/organon/findings_closed_v.test.ts \
  test/organon/findings_closed_voice.test.ts \
  test/organon/findings_closed_surface.test.ts \
  test/organon/findings_closed_sovereign.test.ts \
  test/organon/findings_closed_interpret.test.ts \
  test/organon/findings_closed_b.test.ts \
  test/organon/voice_gates.test.ts \
  test/organon/voice_contract.test.ts \
  test/organon/voice_intents.test.ts \
  test/organon/cal_ledger.test.ts \
  test/organon/voice_eval.test.ts \
  test/organon/eval_live.test.ts \
  test/organon/stamp_mintrl.test.ts \
  test/organon/voice_redteam.test.ts \
  test/organon/contract_extract.test.ts \
  test/organon/contract_subaxis.test.ts \
  test/organon/contract_ingest.test.ts \
  test/organon/contract_buildcapture.test.ts \
  test/organon/contract_registry_real.test.ts \
  test/organon/contract_redteam.test.ts \
  test/organon/contract_verify_redteam.test.ts \
  test/organon/ask_live.test.ts \
  test/organon/decay.test.ts \
  test/organon/icir.test.ts \
  test/organon/persistence_redteam.test.ts \
  test/organon/surface_system.test.ts \
  test/organon/surface_content_identity.test.ts \
  test/organon/surface_a11y.test.ts \
  test/organon/surface_detector.test.ts \
  test/organon/surface_redteam.test.ts \
  test/organon/surface_designpass.test.ts \
  test/organon/plane_funding.test.ts \
  test/organon/plane_events.test.ts \
  test/organon/plane_rpcstate.test.ts \
  test/organon/sovereign_redteam.test.ts \
  test/organon/interpret_redteam.test.ts \
  test/organon/lineage_diagnosis.test.ts \
  test/organon/lineage_walls.test.ts \
  test/organon/lineage_fix.test.ts \
  test/organon/lineage_redteam.test.ts
