/**
 * ORGΛNON — THE REACH SPRINT (V35), Phase 3 wall: S93 — THE FALSIFIABILITY CENSUS (X-REACH(a) made mechanical).
 *
 * "A check that cannot fail is not a check." Every wall S1-S99 is bucketed by a PURE READ over the committed test tree
 * (Falsify.census — RP-6: a living wall, not a document; regenerated by the battery). DEMONSTRATED requires a NAMED
 * originating defect (a W-tag) — never an invented origin (RP-1, the exact unfalsifiable claim this sprint was minted to
 * end). The headline is the uncomfortable one: the majority of walls have NO recorded originating defect. A wall added
 * with no bucket, or a wall id beyond the pinned range, FAILS the battery.
 */
import { test, expect } from "bun:test"
import { readFileSync } from "node:fs"
import { createHash } from "node:crypto"
import path from "node:path"
import { PKG_ROOT } from "../../src/organon/frozen"
import { Falsify } from "../../src/organon/falsify"

const committed = JSON.parse(readFileSync(path.join(PKG_ROOT, "data", "honesty", "falsifiability-census.json"), "utf8"))
const live = Falsify.census()

test("S93 — the census REPRODUCES: the live pure-read derivation matches the committed content hash (RP-6 — regenerated by the battery, never hand-written)", () => {
  // Derivation V36 (S104): `route` is part of the canonical — a re-founded/recovered wall's treatment moves the hash.
  const canonical = JSON.stringify(live.rows.map((r) => ({ id: r.id, bucket: r.bucket, hasControl: r.hasControl, recordedOrigin: r.recordedOrigin, originStrength: r.originStrength, route: r.route, decoration: r.decoration })))
  const liveSha = createHash("sha256").update(canonical).digest("hex")
  expect(liveSha).toBe(committed.contentSha) // a drift here means a wall was added/changed without regenerating the census
  expect(live.counts).toEqual(committed.counts)
  expect(live.wallCount).toBe(committed.wallCount)
})

test("S93 — EVERY referenced wall is in exactly one of the four buckets (a wall in no bucket cannot exist by construction)", () => {
  const buckets = new Set(["DEMONSTRATED", "WEAK", "EXEMPT", "ORIGIN_UNRECORDED"])
  for (const r of live.rows) expect(buckets.has(r.bucket)).toBe(true)
  const sum = live.counts.DEMONSTRATED + live.counts.WEAK + live.counts.EXEMPT + live.counts.ORIGIN_UNRECORDED
  expect(sum).toBe(live.wallCount) // the four buckets partition the wall set exactly
})

test("S93/RP-6 — the living wall: a test that references a wall id beyond the pinned range (S>99) is an ORPHAN and FAILS the census", () => {
  expect(live.orphans).toEqual([]) // none today
  // the mechanism is real: orphanWallIds scans the whole test tree; a future wall numbered beyond the pinned range is
  // caught and must be consciously admitted. Proven directly — the id is BUILT at runtime so no ">99" token appears
  // literally in this file (which would make the census flag its own test — the living wall really does bite).
  const futureId = "S" + "191"
  const injected = [{ file: "x", text: `test(${JSON.stringify(futureId + " — a hypothetical future wall")})` }] as unknown as { file: string; text: string }[]
  expect(Falsify.orphanWallIds(injected)).toEqual([futureId])
  expect(Falsify.WALL_MAX).toBe(180) // Provenance Sprint V42: bumped 170→180 for the S169..S179 band (identity gate + REAL★ capture engine / RETROSPECTIVE boundary / capture window; consciously admitted)
})

test("S93/RP-1 — DEMONSTRATED is the STRONG claim and is never invented: every DEMONSTRATED wall carries a NAMED originating defect (a W-tag) OR a treatment route (S104)", () => {
  const demonstrated = live.rows.filter((r) => r.bucket === "DEMONSTRATED")
  expect(demonstrated.length).toBeGreaterThan(0)
  for (const r of demonstrated) {
    expect(r.hasControl).toBe(true) // a demonstrated failure — always
    // Derivation V36 (S104): DEMONSTRATED is earned by EITHER a NAMED originating defect (W-tag — remembered/recovered)
    // OR a treatment route (recovered / re-founded). A re-founded wall carries route "reFounded" + a stated defect + a
    // seeded negative — never an invented W-tag (RP-1: a purpose reconstructed is not dressed up as a purpose remembered).
    const earned = r.originStrength === "W-TAG" || r.route === "recovered" || r.route === "reFounded"
    expect({ id: r.id, earned }).toEqual({ id: r.id, earned: true })
    if (r.route === null) expect(r.recordedOrigin).toMatch(/^W-[A-Z]/) // an untreated DEMONSTRATED wall still needs its W-tag
  }
})

test("S93 — the EXEMPT class is ENUMERATED with reasons (never silently excused, X-REACH(a))", () => {
  const exempt = live.rows.filter((r) => r.bucket === "EXEMPT")
  for (const r of exempt) {
    expect(r.note.length).toBeGreaterThan(20) // a real reason
    expect(r.note).toMatch(/grep-wall|structural absence|unrepresentable/i)
  }
})

test("S93 — the headline, updated to a MILESTONE: DEMONSTRATED has reached parity with ORIGIN_UNRECORDED (the project has graded as many tests as not) — stated, not hidden", () => {
  // For many sprints the census's uncomfortable finding was that ORIGIN_UNRECORDED was the LARGEST bucket — the project had
  // not graded its own tests. PROVENANCE V42: SEVEN sprints of W-tagged walls + the S104 treatment have driven OU DOWN from the
  // V35 baseline of 83 and DEMONSTRATED UP, and this sprint's identity + capture walls (S169–S179, all W-tagged with seeded
  // negatives) bring DEMONSTRATED to PARITY WITH OR PAST OU — a real milestone, stated not spun: for the first time, at least
  // as many walls carry a NAMED originating defect as do not. OU and DEMONSTRATED remain the two dominant buckets, each far
  // above EXEMPT/WEAK; the count of ungraded walls is still named out loud (never hidden), it has simply stopped being the largest.
  expect(live.counts.DEMONSTRATED).toBeGreaterThanOrEqual(live.counts.ORIGIN_UNRECORDED) // DEMONSTRATED has caught up — the milestone
  expect(live.counts.ORIGIN_UNRECORDED).toBeGreaterThan(live.counts.EXEMPT)
  expect(live.counts.DEMONSTRATED).toBeGreaterThan(live.counts.EXEMPT)
  expect(live.counts.ORIGIN_UNRECORDED + live.counts.DEMONSTRATED).toBeGreaterThan(live.wallCount * 0.9) // the two dominate the partition
  expect(committed.headline).toMatch(/NO recorded originating defect/i) // the ungraded count is still stated, not hidden
})

test("S93 — the no-seeded-negative count is a STATED heuristic flag (attack #10), under a pinned ceiling; a new decoration raises it visibly", () => {
  // the flag is a LOWER BOUND for the auditor, not a proof — it is counted, never dropped. The pinned ceiling makes a
  // NEW control-less wall FAIL the battery until it is given a control or consciously acknowledged (RP-6, living).
  const CEILING = 5
  expect(live.decorationCount).toBeLessThanOrEqual(CEILING)
  expect(committed.noSeededNegativeFlag.meaning).toMatch(/NOT a proof the wall cannot fail/i)
  expect(committed.noSeededNegativeFlag.count).toBe(live.decorationCount)
})
