/**
 * ORGΛNON — THE DERIVATION SPRINT (V36), Phase 6: the RESIDUES (MR9 · MR10 · MR11 · README line) made concrete.
 *
 * MR9 (attribution) and MR12 (the Halt-not-a-shield shelving) are asserted by derive_pins + mr1_census. This wall pins the
 * two remaining concrete residues: MR10 — the FULL auto-discover battery and the CURATED verify subset are DISTINCT surfaces
 * with distinct counts, never conflated (V35's marker mixed 1281/197 with 1281/0); MR11 — the ±3 expect() jitter did not
 * reproduce (the candidate loop/differential tests are stable across runs), so the standing convergence guard (two identical
 * expect() runs, no band) is the wall; and the README positioning line, taken from the competitor because it is better.
 */
import { test, expect } from "bun:test"
import { readFileSync } from "node:fs"
import path from "node:path"
import { PKG_ROOT } from "../../src/organon/frozen"

const H = path.join(PKG_ROOT, "data", "honesty")
const dp = JSON.parse(readFileSync(path.join(H, "derive-pins.json"), "utf8"))

test("MR10 — the battery notation is reconciled: the CURATED verify subset (battery-summary.json) is a DISTINCT surface from the FULL auto-discover battery, never conflated", () => {
  const curated = JSON.parse(readFileSync(path.join(H, "evidence", "battery-summary.json"), "utf8")).canonical
  // the curated subset is pass/fail over a FILE count (what `verify` diffs) — a distinct shape from the full pass/skip/fail
  expect(typeof curated.pass).toBe("number")
  expect(typeof curated.files).toBe("number")
  expect(curated.fail).toBe(0)
  // the pin states the two are distinct surfaces (the fix for V35's 1281/197 vs 1281/0 conflation)
  expect(dp.mr10_notation.rule).toMatch(/DISTINCT surfaces/i)
})

test("MR11 — the jitter is diagnosed: the pin records it as unreproduced, and the standing guard (two identical expect() runs, no band) is named (X-DETERM admits no tolerance)", () => {
  expect(dp.mr11_jitter.rule).toMatch(/DIAGNOSED/i)
  expect(dp.mr11_jitter.s99Carried).toMatch(/two identical expect\(\) runs|no band/i)
})

test("MR9 — the attribution discipline is pinned, and X-DERIVE retires it structurally (the per-phase markers are GENERATED, so an unattributed test cannot slip)", () => {
  expect(dp.mr9_unattributedTests.rule).toMatch(/itemized/i)
  expect(dp.mr9_unattributedTests.rule).toMatch(/GENERATED by Rollup|cannot slip/i)
})

test("the README carries the positioning line (documentation — permitted, not capability): 'a methodology audit, not investment advice'", () => {
  const readme = readFileSync(path.join(PKG_ROOT, "README.md"), "utf8")
  expect(readme).toMatch(/methodology audit, not investment advice/i)
})
