/**
 * ORGΛNON DATA-PLANE — the standalone-native PIT store + the DataAdapter seam (Data-Plane Phase 1; Rules D-SEAM,
 * D-LABEL, L-TICK). The real-data body left behind at the transplant comes home here — but standalone-native BY
 * CONSTRUCTION: flat JSON + JSONL (the same storage idiom as the rest of the studio), NO SQLite, NO OpenCode schema, NO
 * sibling packages (the leak wall makes that structural). Snapshots are content-addressed + immutable; their provenance
 * is a hash-chained, nonce-anchored Capture.Service chain (reused verbatim), so a retro-captured or tampered snapshot
 * cannot verify. `asOf(key, ts)` is strict point-in-time (the last point at or before ts) — the no-lookahead guarantee.
 *
 * The DataAdapter interface is the seam the ported Runner sees (interfaces, not schemas). Domains read through it; they
 * never reach into storage. A snapshot the store cannot resolve is ABSENT (honest), never a fabricated payload.
 */
import { createHash } from "node:crypto"
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import path from "node:path"
import { PKG_ROOT } from "../organon/frozen"
import { Capture } from "../studio/capture"

export namespace DataPlane {
  export type Kind = "yield" | "price" | "rate" | "volume"
  export interface SeriesPoint {
    ts: number
    [field: string]: number | null
  }
  // the currency D-LABEL spends: a REAL-PIT label requires one of these, resolving to a chained snapshot
  export interface Provenance {
    source: string // e.g. "defillama:yields.llama.fi/chart"
    url: string
    capturedAt: number
    contentSha: string // sha256 of the canonical snapshot payload — the immutable anchor
    nonce: string // the capture-time secret (Capture.Service) — a retro-capture cannot reproduce it
    chainPos: number // position in the domain's provenance chain
    reality: "REAL-PIT" | "ILLUSTRATIVE" | "BLOCKED"
  }
  export interface Series {
    key: string
    kind: Kind
    points: SeriesPoint[]
    provenance: Provenance
  }

  // The seam. The ported Runner/reexec see THIS, never storage. A swap of the backing store never reaches a domain.
  export interface Adapter {
    name: string
    listSeries(): string[]
    fetchSeries(key: string): Series | null
    provenance(key: string): Provenance | null
  }

  const sha256 = (b: string) => createHash("sha256").update(b).digest("hex")
  const ROOT = path.join(PKG_ROOT, "data", "dataplane")
  const SNAP_DIR = path.join(ROOT, "snapshots")
  const PROV_FILE = path.join(ROOT, "provenance.jsonl")

  // canonical payload serialization — stable across machines so the content sha is reproducible (byte-identical)
  export interface SnapshotFile {
    key: string
    kind: Kind
    source: string
    url: string
    capturedAt: number
    points: SeriesPoint[]
  }
  export function canonical(snap: SnapshotFile): string {
    // deterministic: sorted points by ts, fields in a fixed order, no whitespace drift
    const pts = [...snap.points].sort((a, b) => a.ts - b.ts)
    return JSON.stringify({ key: snap.key, kind: snap.kind, source: snap.source, url: snap.url, points: pts })
  }
  export function contentSha(snap: SnapshotFile): string {
    return sha256(canonical(snap))
  }

  function ensureDirs() {
    if (!existsSync(ROOT)) mkdirSync(ROOT, { recursive: true })
    if (!existsSync(SNAP_DIR)) mkdirSync(SNAP_DIR, { recursive: true })
  }

  function provenanceService(): Capture.Service {
    ensureDirs()
    return new Capture.Service(PROV_FILE) // throws if the chain is broken (tamper detection, reused verbatim)
  }

  // ── capture: write a content-addressed immutable snapshot + a nonce-anchored provenance stamp ────────────────────
  // The nonce is generated by Capture.Service AT CAPTURE TIME — a backfilled/retro-captured snapshot cannot verify.
  // A missed capture is simply never written (a GAP the status renders); interpolation/smoothing has no code path here.
  export interface CaptureResult { key: string; contentSha: string; nonce: string; chainPos: number; snapshotPath: string }
  export function capture(snap: SnapshotFile, meta?: { origin?: Capture.Stamp["origin"]; schedulerRun?: string }): CaptureResult {
    ensureDirs()
    const csha = contentSha(snap)
    const keyDir = path.join(SNAP_DIR, snap.key.replace(/[^a-zA-Z0-9._-]/g, "_"))
    if (!existsSync(keyDir)) mkdirSync(keyDir, { recursive: true })
    const snapshotPath = path.join(keyDir, `${csha}.json`)
    if (!existsSync(snapshotPath)) writeFileSync(snapshotPath, canonical(snap) + "\n") // content-addressed ⇒ immutable
    const svc = provenanceService()
    const stamp = svc.capture(snap.key, canonical(snap), snap.capturedAt, meta)
    const chainPos = svc.all().filter((s) => s.domain === snap.key).length - 1
    return { key: snap.key, contentSha: csha, nonce: stamp.nonce, chainPos, snapshotPath }
  }

  // resolve the latest verifying snapshot for a key, or null (ABSENT — honest, never fabricated)
  function latestStamp(key: string): Capture.Stamp | null {
    if (!existsSync(PROV_FILE)) return null
    const svc = provenanceService() // re-verifies the whole chain on construct
    const forKey = svc.all().filter((s) => s.domain === key)
    return forKey.length ? forKey[forKey.length - 1] : null
  }

  export function loadSnapshotFile(key: string, csha: string): SnapshotFile | null {
    const p = path.join(SNAP_DIR, key.replace(/[^a-zA-Z0-9._-]/g, "_"), `${csha}.json`)
    if (!existsSync(p)) return null
    return { ...(JSON.parse(readFileSync(p, "utf8")) as Omit<SnapshotFile, "capturedAt">), capturedAt: 0 } as SnapshotFile
  }

  // The standalone-native snapshot adapter — the default Adapter implementation over the immutable snapshot store.
  export const snapshotAdapter: Adapter = {
    name: "standalone-snapshot",
    listSeries(): string[] {
      if (!existsSync(PROV_FILE)) return []
      const svc = provenanceService()
      return [...new Set(svc.all().map((s) => s.domain))]
    },
    fetchSeries(key: string): Series | null {
      const stamp = latestStamp(key)
      if (!stamp) return null
      const snap = loadSnapshotFile(key, stamp.payloadSha)
      if (!snap) return null
      // integrity: the snapshot on disk MUST hash to the provenance stamp's payloadSha, else tampered → refuse (never serve)
      if (contentSha({ ...snap, capturedAt: stamp.capturedAt }) !== stamp.payloadSha) return null
      const prov = this.provenance(key)!
      return { key, kind: snap.kind, points: [...snap.points].sort((a, b) => a.ts - b.ts), provenance: prov }
    },
    provenance(key: string): Provenance | null {
      const stamp = latestStamp(key)
      if (!stamp) return null
      const snap = loadSnapshotFile(key, stamp.payloadSha)
      if (!snap) return null
      const chainPos = provenanceService().all().filter((s) => s.domain === key).length - 1
      return { source: snap.source, url: snap.url, capturedAt: stamp.capturedAt, contentSha: stamp.payloadSha, nonce: stamp.nonce, chainPos, reality: "REAL-PIT" }
    },
  }

  // strict point-in-time: the last point at or before ts (bisect). No lookahead, ever.
  export function asOf(series: Series, ts: number): SeriesPoint | null {
    let lo = -1
    for (let i = 0; i < series.points.length; i++) {
      if (series.points[i].ts <= ts) lo = i
      else break
    }
    return lo >= 0 ? series.points[lo] : null
  }

  // the window over which the series has data
  export function window(series: Series): { start: number; end: number } | null {
    if (!series.points.length) return null
    return { start: series.points[0].ts, end: series.points[series.points.length - 1].ts }
  }

  // the store's rendered state per key: PRESENT (with chain depth) / ABSENT — never smoothed, never faked
  export function status(adapter: Adapter, key: string): { key: string; present: boolean; render: string } {
    const s = adapter.fetchSeries(key)
    if (!s) return { key, present: false, render: `${key}: ABSENT — no verifying snapshot (honest; never a fabricated payload)` }
    const w = window(s)!
    return { key, present: true, render: `${key}: PRESENT — ${s.points.length} pts [${new Date(w.start).toISOString().slice(0, 10)}..${new Date(w.end).toISOString().slice(0, 10)}], provenance ${s.provenance.contentSha.slice(0, 12)}… (nonce-anchored, chain pos ${s.provenance.chainPos})` }
  }

  // verify the whole committed provenance chain (nonce-anchored, hash-chained) — throws via Capture.Service if broken.
  // Returns the per-key snapshot depth. On a fresh clone (no provenance file) returns absent, disclosed (never faked).
  export function verifyProvenanceChain(): { present: boolean; ok: boolean; keys: Record<string, number>; total: number } {
    if (!existsSync(PROV_FILE)) return { present: false, ok: true, keys: {}, total: 0 }
    const svc = provenanceService() // constructs → re-verifies; throws on a broken/retro/tampered chain
    const v = svc.verify()
    const keys: Record<string, number> = {}
    for (const s of svc.all()) keys[s.domain] = (keys[s.domain] ?? 0) + 1
    return { present: true, ok: v.ok, keys, total: svc.all().length }
  }

  // ── the CAPTURE FLOOR (Reachability Phase 1; Rule R-BASIS, A′) — formalized: a live venue's capture is admissible as
  // chained only at ≥3 chained stamps across ≥2 distinct runs. The V11 basis capture sat below the store's own V9
  // precedent (which committed its provenance chain); this names the floor as a constant and asserts it per venue.
  export const CAPTURE_FLOOR = { minChainedStamps: 3, minRuns: 2 } as const
  export function venueFloorStatus(venuePrefix: string): { present: boolean; stamps: number; runs: number; meetsFloor: boolean } {
    if (!existsSync(PROV_FILE)) return { present: false, stamps: 0, runs: 0, meetsFloor: false }
    const svc = provenanceService() // re-verifies the chain on construct (a tamper/retro/backfill throws)
    const forVenue = svc.all().filter((s) => s.domain.includes(venuePrefix))
    const runs = new Set(forVenue.map((s) => s.capturedAt)).size
    return { present: true, stamps: forVenue.length, runs, meetsFloor: forVenue.length >= CAPTURE_FLOOR.minChainedStamps && runs >= CAPTURE_FLOOR.minRuns }
  }

  export const paths = { ROOT, SNAP_DIR, PROV_FILE }
}
