/**
 * ORGΛNON — THE REACH SPRINT (V35), S93: regenerate the FALSIFIABILITY CENSUS (X-REACH(a) made mechanical).
 *
 * A PURE READ over the committed test tree (Falsify.census) — never a hand-written document (RP-6), never an invented
 * origin (RP-1). Publishes data/honesty/falsifiability-census.json, content-hashed, with the DECORATION count (the
 * heuristic "no seeded-negative signal" flag) stated OUT LOUD. The headline is the uncomfortable one this phase exists to
 * state: how many of ninety-nine walls have NEVER had their originating defect recorded — the project grading itself.
 *
 * Run: bun run script/honesty/falsifiability-census.ts
 */
import { createHash } from "node:crypto"
import { writeFileSync } from "node:fs"
import path from "node:path"
import { PKG_ROOT } from "../../src/organon/frozen"
import { Falsify } from "../../src/organon/falsify"

const c = Falsify.census()
// a canonical content hash over the derived rows (deterministic order → reproducible; RP-6)
const canonical = JSON.stringify(c.rows.map((r) => ({ id: r.id, bucket: r.bucket, hasControl: r.hasControl, recordedOrigin: r.recordedOrigin, originStrength: r.originStrength, decoration: r.decoration })))
const contentSha = createHash("sha256").update(canonical).digest("hex")

const record = {
  protocol: "falsifiability-census",
  at: "2026-07-14",
  rule: "S93 — every wall S1-S99 bucketed by a PURE READ over the committed test tree (Falsify.census). DEMONSTRATED = a seeded negative + a NAMED originating defect (a W-xxNN tag) in the committed context. WEAK = a recorded origin whose negative is arbitrary (to strengthen). EXEMPT = a reasoned structural-absence grep-wall (enumerated, never silently excused). ORIGIN_UNRECORDED = a control but NO recorded originating defect — the majority, and the honest one (RP-1: a census that pretends to know why 99 walls exist is the unfalsifiable claim this sprint was minted to end).",
  method: "mechanical + transparent: hasControl (a seeded-negative / must-fail / degraded-verdict / determinism idiom), recordedOrigin (a committed W-tag or sprint re-pin reference — the untracked build logs do NOT count, so the census is clone-stable), structuralAbsence, and a short curated EXEMPT/WEAK override set (reasoned). The regexes are documented in src/organon/falsify.ts.",
  wallCount: c.wallCount,
  counts: c.counts,
  originStrength: { wTag: c.rows.filter((r) => r.originStrength === "W-TAG").length, reference: c.rows.filter((r) => r.originStrength === "REFERENCE").length },
  noSeededNegativeFlag: {
    count: c.decorationCount,
    walls: c.rows.filter((r) => r.decoration).map((r) => r.id),
    meaning: "a HEURISTIC LOWER BOUND (attack #10, stated not hidden): the scan found no explicit demonstrated-failure signal in the committed context. NOT a proof the wall cannot fail — a flag for the auditor. Walls whose test files land later in this sprint (S96-S98) resolve on the next regenerate.",
  },
  headline: `${c.counts.ORIGIN_UNRECORDED} of ${c.wallCount} walls have NO recorded originating defect in their committed context — the project has, until now, never systematically asked whether its own tests can fail (X-REACH(a), attack #1). ${c.counts.DEMONSTRATED} are DEMONSTRATED (a named defect + a seeded negative); ${c.counts.EXEMPT} are reasoned structural-absence exemptions; ${c.decorationCount} carry no seeded-negative signal at all (flagged).`,
  livingWall: "RP-6 — this is regenerated by the battery (Falsify.census is a pure read); a wall id referencing S(>99) is an ORPHAN and FAILS the census until the range is consciously bumped. A wall added with no seeded negative raises the flagged count, visibly.",
  orphans: c.orphans,
  contentSha,
  rows: c.rows,
}

writeFileSync(path.join(PKG_ROOT, "data", "honesty", "falsifiability-census.json"), JSON.stringify(record, null, 2) + "\n")

console.log("── REACH — the falsifiability census (S93) ─────────────────")
console.log(`  walls              : ${c.wallCount}`)
console.log(`  DEMONSTRATED       : ${c.counts.DEMONSTRATED} (all W-tag named defects)`)
console.log(`  WEAK               : ${c.counts.WEAK}`)
console.log(`  EXEMPT             : ${c.counts.EXEMPT} (reasoned structural absence)`)
console.log(`  ORIGIN_UNRECORDED  : ${c.counts.ORIGIN_UNRECORDED}  ← the headline`)
console.log(`  no-seeded-negative : ${c.decorationCount} flagged (${c.rows.filter((r) => r.decoration).map((r) => r.id).join(", ")})`)
console.log(`  content sha        : ${contentSha.slice(0, 16)}…`)
console.log(`  ${record.headline}`)
console.log("  record written: data/honesty/falsifiability-census.json")
